project:
  type: book

book:
  title: "Pensamiento estadístico"
  author: "Felipe González y Michelle Anzarut"
  date: "5/3/2022"
  chapters:
    - index.qmd
    - est_cd.qmd
    - analisis_exp.qmd
    - inferencia-1.qmd
    - referencias.qmd

bibliography: referencias.bib

format:
  html:
    theme: cosmo
    lang: es



