project:
  type: book

book:
  title: "Pensamiento estadístico"
  author: "Felipe González y Michelle Anzarut"
  date: "7/25/2022"
  chapters:
    - index.qmd
    - part: 01-est-cd-1.qmd
    - part: 02-resumenes.qmd
      chapters:
        - 02-resumenes-analisis-1.qmd
        - 02-resumenes-analisis-2.qmd
    - part: 03-intro-inferencia.qmd
      chapters:
        - 03-intro-pruebas-hipotesis.qmd
        - 03-pruebas-hipotesis-aleatorizacion.qmd
#        - 03-pruebas-hipotesis-2.qmd
#        - 03-pruebas-hipotesis-3.qmd
#    - part: 04-estimacion.qmd
#      chapters:
#        - 04-estimacion-aleatorizacion.qmd
#        - 04-estimacion-remuestreo.qmd
#    - part: 05-probabilidad.qmd
#      chapters:
#        - 05-prob-modelos.qmd
#        - 05-prob-condicional.qmd
#        - 05-prob-modelos-continuos.qmd
#    - part: 06-inferencia-modelos.qmd
#      chapters:
#        - 06-maxima-verosimilitud.qmd
#        - 06-intro-bayesiana-1.qmd
#        - 06-intro-bayesiana-2.qmd
bibliography: referencias.bib

format:
  html:
    theme: cosmo
    lang: es
    code-fold: true



