project:
  type: book

book:
  title: "Pensamiento estadístico"
  author: "Felipe González y Michelle Anzarut"
  date: "5/3/2022"
  chapters:
    - index.qmd
    - part: est-cd-1.qmd
    - part: resumenes.qmd
      chapters:
        - analisis-resumenes-1.qmd
        - analisis-resumenes-2.qmd
    - part: intro-inferencia.qmd
      chapters:
        - intro-pruebas-hipotesis.qmd
        - pruebas-hipotesis-aleatorizacion.qmd
        - pruebas-hipotesis-2.qmd
        - estimacion-aleatorizacion.qmd
        - remuestreo-bootstrap.qmd
    - part: probabilidad.qmd
      chapters:
        - modelo-prob.qmd
        - prob-condicional.qmd
        - modelos-continuos.qmd
        - inferencia-modelos.qmd
    - part: inferencia-bayesiana.qmd
      chapters:
        - intro-bayesiana-1.qmd
        - intro-bayesiana-2.qmd
bibliography: referencias.bib

format:
  html:
    theme: cosmo
    lang: es
    code-fold: true



